# Generated by Django 6.0.1 on 2026-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_churchdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
